# Generated by Django 2.0.7 on 2018-07-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opremain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narcotic',
            old_name='keyword_name',
            new_name='keyword',
        ),
    ]
