# Generated by Django 2.0.7 on 2018-07-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opremain', '0002_auto_20180712_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narcotic',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='판매사'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='keyword',
            field=models.CharField(max_length=50, verbose_name='키워드'),
        ),
    ]
