# Generated by Django 2.0.7 on 2018-07-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opremain', '0003_auto_20180712_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='extra_column',
            new_name='extra_columns',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='essential_column',
            new_name='not_null_columns',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='orderby_column',
            new_name='orderby_columns',
        ),
    ]
