# Generated by Django 2.0.7 on 2018-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opremain', '0005_auto_20180714_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='설정제목'),
        ),
    ]
