# Generated by Django 2.0.7 on 2018-07-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opremain', '0006_auto_20180714_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='extra_columns',
            field=models.TextField(verbose_name='표기할컬럼'),
        ),
    ]
