# Generated by Django 2.0.7 on 2018-07-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opremain', '0007_auto_20180714_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='extra_columns',
            field=models.TextField(blank=True, null=True, verbose_name='표기할컬럼'),
        ),
        migrations.AlterField(
            model_name='config',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='설정제목'),
        ),
    ]
